### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by WatsonWangZh** [THUDM/SelfKG#1]
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    trainer = Trainer(seed=2020)
  File "/home/wangzhen/program/GraduationProject/SelfKG/model/layers.py", line 315, in __init__
    myset1 = Mydataset(token1.id_features_dict)  # dataset
TypeError: __init__() missing 1 required positional argument: 'adj_tensor_dict'

**Comment by WatsonWangZh** [comment]
@Xiao9905 xiao

**Comment by Xiao9905** [comment]
Thanks for your reminder, we will fix it up this weekend!

**Comment by WatsonWangZh** [comment]
File "run_DWY_neighbor.py", line 7, in <module>
    trainer.train(0)
  File "model/layers_DWY_neighbor.py", line 442, in train
    pkl = open(join(DATA_DIR, 'DWY100K', self.args.dir, "epochs_32_64", "batch_{}".format(epoch) + ".pkl"), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/DWY100K/dbp_wd/epochs_32_64/batch_0.pkl'
@Xiao9905 How to get the pickle file?

**Comment by Xiao9905** [comment]
@WatsonWangZh The codes are now published. Thanks for your interest in our work.

**Comment by WatsonWangZh** [comment]
Thanks for your prompt reply. Great job.

**Comment by WatsonWangZh** [comment]
How long does it take to run the LaBSE_SSL experiment? It seems too slow. @Xiao9905

**Comment by HaoyunHong** [comment]
@WatsonWangZh 

> How long does it take to run the LaBSE_SSL experiment? It seems too slow. @Xiao9905

Yes, it is slow, because LaBSE is a large model. But it is only for ablation study with only entity name information, so it's not important. We will delete the ablation study code in the repository.
