### ISSUE TITLE
How to produce dataset

### ISSUE THREAD

**Issue by mhoangvslev** [THUDM/SelfKG#13]
While I understood the general structure of the dataset and how to produce most of the elements, I still can't figure out how `triples_n` files are generated. Can you help me?

**Comment by HaoyunHong** [comment]
Thanks for your attention. As we mentioned in our paper, the DWY100K dataset we use is built by 
```
@inproceedings{sun2018bootstrapping,
  title={Bootstrapping Entity Alignment with Knowledge Graph Embedding},
  author={Sun, Zequn and Hu, Wei and Zhang, Qingheng and Qu, Yuzhong},
  booktitle={ IJCAI, vol.18},
  pages={4396--4402},
  year={2018}
}
```
and the DBP15k we used is built by
```
@inproceedings{JAPE,
  title={Cross-lingual entity alignment via joint attribute-preserving embedding},
  author={Sun, Zequn and Hu, Wei and Li, Chengkai},
  booktitle={ISWC},
  pages={628--644},
  year={2017},
  organization={Springer}
}
```

The dataset we provided is based on the original datasets mentioned above : )

**Comment by mhoangvslev** [comment]
According to BootEA papers
> We then extracted all the triples that only involve the entities in the alignment.

I understood it like this: they extract all entities (e1, e2) that connect directly to entity e.

**Comment by HaoyunHong** [comment]
A triple is like (e1, r, e2), where r is the relation between entity e1 and entity e2. 

I think this sentence:

> We then extracted all the triples that only involve the entities in the alignment.

means that if a triple contains an entity e_a  in Knowledge Graph KG_a that has an equivalent entity e_b in the other Knowledge Graph KG_b, that means e_a is in the alignment, then they extract this triple into their dataset.

**Comment by mhoangvslev** [comment]
In their dataset, they extract concepts of different themes. Therefore it is possible for them to extract entities and relationships between them. My case is a bit different. I only need to align entities of one theme (e.g Airports), and it's impossible to find an Aiport that is 1 op (relationship) away to another airport. My training set thus contains non-Airport entities, will it affect my results?

**Comment by HaoyunHong** [comment]
Sorry, your question is not very clear to me and is not related to this project. Maybe others can help you with your question : )
