### ISSUE TITLE
关于初始嵌入向量的问题

### ISSUE THREAD

**Issue by kilinchange** [THUDM/SelfKG#15]
您好，我注意到你们代码里提供的初始嵌入向量文件 ./data/DBP15K/zh_en/raw_LaBSE_emb_1.pkl 与./data/DBP15K/zh_en/raw_LaBSE_emb_2.pkl 包含5244个重合的向量，感觉初始嵌入向量的重合率有点大，请问这是 LaBSE 在未使用翻译技术的前提下得到的嵌入向量，还是使用了翻译技术后得到的嵌入向量呢？如果是后者，请问可以提供未使用翻译技术的嵌入向量吗？
另外，请问可以提供不使用翻译技术、嵌入模型为 FastText 的初始嵌入向量吗？
期待您的回复！谢谢！

**Comment by 2445265988** [comment]
您好，由于zenodo网址无法访问，您代码中的数据集无法下载，如果可以方便重新提供一下数据吗？

**Comment by Xiao9905** [comment]
@2445265988 Hi，可以尝试从临时链接下载：https://cloud.tsinghua.edu.cn/f/d099c749c3944b419850/

**Comment by 2445265988** [comment]
非常感谢您的回复！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月17日(周五) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: "shiyu ***@***.******@***.***&gt;;
主题: Re: [THUDM/SelfKG] 关于初始嵌入向量的问题 (Issue #15)




 
@2445265988 Hi，可以尝试从临时链接下载：https://cloud.tsinghua.edu.cn/f/d099c749c3944b419850/
