### ISSUE TITLE
File Error

### ISSUE THREAD

**Issue by abc575** [THUDM/SelfKG#4]
Thanks for your great work. When I run your model on different datasets you provided, I found there are maybe some missing files and corrupted file. 

For DBP15K fr_en and DWY100K dbp_yg, some files seem corrupted and unreadable. There are errors like (both  DBP15K fr_en and DWY100K dbp_yg):
Traceback (most recent call last):
  File "run_LaBSE_neighbor.py", line 5, in <module>
    trainer = Trainer(seed=37)
  File "SelfKG/model/layers_LaBSE_neighbor.py", line 193, in __init__
    loader1 = DBP15KRawNeighbors(self.args.language, "1")
  File "SelfKG/loader/DBP15KRawNeighbors.py", line 16, in __init__
    self.load()
  File "SelfKG/loader/DBP15KRawNeighbors.py", line 22, in load
    self.id_entity = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\x00'.

For DWY100K dataset, some files may be missing, there is error like:
No such file or directory: 'SelfKG/data/DWY100K/dbp_wd/valid.ref'

**Comment by HaoyunHong** [comment]
Hi @abc575 

Thanks very much for your interest! Maybe the corrupted files result from unsuccessful dataset downloads from the Internet. We will deal with these issues soon and provide a more stable dataset download link for all the readers.

**Comment by HaoyunHong** [comment]
Hi @abc575 

Our new download link is [here](https://zenodo.org/record/6326870#.YigQEHxBxPZ), which is also updated in our [README](https://github.com/THUDM/SelfKG#data-preparation) : )
