### ISSUE TITLE
paper not found

### ISSUE THREAD

**Issue by SherryTTK** [THUDM/SelfKG#6]
Thank you for this great work
I cant find the paper from the paper link
Could you help me
Thanks again

**Comment by Xiao9905** [comment]
Hi @Yasuo-orphan 

Thanks for your interest in our work! The paper has not been ready on arxiv, so please wait a little bit until we finish the final version. We will inform you once we finish (should be in 1-2 weeks).

**Comment by SherryTTK** [comment]
@Xiao9905 
Thanks again :D

**Comment by HaoyunHong** [comment]
Hi @Yasuo-orphan

Thanks for your interest! Our paper is now available [here](https://arxiv.org/abs/2203.01044) : )
#6
