### ISSUE TITLE
Missing file again

### ISSUE THREAD

**Issue by sunhao123456789** [THUDM/SelfKG#8]
No module named 'model.layers_LaBSE_SSL',your model file don't have layers_LaBSE_SSL.py. Please sure the run_LaBSE_SSL.py can run. Thanks!

**Comment by HaoyunHong** [comment]
Hi @sunhao123456789 

Thanks for pointing this out. 

Code `run_DWY_LaBSE_neighbor.py` can produce the results of SelfKG on DWY100k, and `run_LaBSE_neighbor.py` can produce the results of SelfKG on DBP15k. These two are the complete implementations of SelfKG.

`run_LaBSE_SSL_DWY.py`, `run_LaBSE_SSL.py` and other `run_LaBSE_*.py` are the ablation study codes for SelfKG without neighbor aggregator on DWY100k or DBP15k. we have uploaded `model/layers_LaBSE_SSL_DWY.py` and `model/layers_LaBSE_SSL.py`. 

Other ablation study codes `run_LaBSE_*.py` and `model/layers_LaBSE_*.py` will be available soon. We are now testing all the codes carefully. 

Thanks!

**Comment by sunhao123456789** [comment]
Hi Dear，Missing File Again!!!
When i run the&nbsp;run_LaBSE_SSL.py,&nbsp;ModuleNotFoundError: No module named 'script.preprocess.deal_fasttext'. Could you download the github SelfKG to run the run_LaBSE_SSL.py???, Too many files missed. Thanks!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月4日(星期五) 上午10:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/SelfKG] Missing file again (Issue #8)





 
Hi @sunhao123456789
 
Thanks for pointing this out.
 
Code run_DWY_LaBSE_neighbor.py can produce the results of SelfKG on DWY100k, run_LaBSE_neighbor.py can produce the results of SelfKG on DBP15k, which are the results of our complete model.
 
run_LaBSE_SSL_DWY.py, run_LaBSE_SSL.py and other run_LaBSE_*.py are the ablation study codes for SelfKG without neighbor aggregator on DWY100k or DBP15k. we have uploaded model/layers_LaBSE_SSL_DWY.py and model/layers_LaBSE_SSL.py.
 
Other ablation study codes will be available soon. We are now testing all the codes carefully.
 
Thanks!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Xiao9905** [comment]
@sunhao123456789 

Dear Sun,

I understand your anxiety in using our code, but please ***be polite*** as all your responses will be presented eternally on github. We are working really hard on solving the problem these two days. Please wait patiently.
