### ISSUE TITLE
Hi Dear, Missing File Again!

### ISSUE THREAD

**Issue by sunhao123456789** [THUDM/SelfKG#9]
When i run the run_LaBSE_SSL.py, ModuleNotFoundError: No module named 'script.preprocess.deal_fasttext'.

**Comment by HaoyunHong** [comment]
Hi @sunhao123456789 

As we've mentioned in #8, we are checking the ablation study code now, including `run_LaBSE_SSL.py`. You may firstly refer to `run_DWY_LaBSE_neighbor.py` and `run_LaBSE_neighbor.py` to produce the results for SelfKG, which we have checked many times. The ablation study code will be available soon. Thanks very much for your understanding!

**Comment by sunhao123456789** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月4日(星期五) 中午11:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/SelfKG] Hi Dear, Missing File Again! (Issue #9)





 
Hi @sunhao123456789
 
As we've mentioned in #8, we are checking the ablation study code now, including run_LaBSE_SSL.py. You may firstly refer to run_DWY_LaBSE_neighbor.py and run_LaBSE_neighbor.py to produce the results for SelfKG, which we have checked many times. The ablation study code will be available soon. Thanks very much for your understanding!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
